---
#
# documentation:
#  - https://docs.pypi.org/trusted-publishers/
#  - https://github.com/astral-sh/trusted-publishing-examples/blob/main/.github/workflows/release.yml
#
name: publish package on TestPyPI

on:
  push:
    tags:
      - v*

jobs:
  build-and-upload:
    name: build package and upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: publish-to-pypi-test
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build package
        run: uv build
      # Check that basic features work and we didn't miss to include crucial files
      # - name: Smoke test (wheel)
      #   run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      # - name: Smoke test (source distribution)
      #   run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py
      - name: Publish package
        run: uv publish
