---
#
# https://coveralls.io/
#

name: update coverage report (coveralls)

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  coverage:
    name: generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: configure Python (using PDM)
        uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: pyproject.toml
      - name: install dependencies
        run: |
          pdm install
      - name: generate coverage report
        run: |
          pdm run coverage run --source=feeph.i2c -m pytest tests/
      - name: coveralls action
        uses: coverallsapp/github-action@v2
